### ISSUE TITLE
Q: Is there a way access hooks from methods and callbacks ?

### ISSUE THREAD

**Issue by cgestes** [rrousselGit/flutter_hooks#112]
The more I use hooks the more I would like them to be accessible from the widget class.

For big widgets I usually have the following:

```dart
class MyWidget extends HookWidget {

  const MyWidget({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final state1Val = useState(...);
    final state2Val = useState(...);

    switch (stateVal.value) {
      case A:
        return _buildA(context, state1Val, state2Val);
      case B:
        return _buildB(context, state1Val, state2Val);
    }
  }

  void _onSomething(context, state1Val, state2Val) {
  }

  Widget _buildA(context, state1Val, state2Val) {
  }

  Widget _buildB(context, state1Val, state2Val) {
  }
}
```
I would like to avoid having to pass the states to all the methods and callbacks.

Tried to experiment with putting all the hooks related function in a buildState function but I wasn't really satisfied, as dart data class are pretty verbose!

I believe that in React hooks are designed with functional component in mind more than with classes.

Maybe we have something to gain by improving the design for classes.

any ideas?

**Comment by rrousselGit** [comment]
How would that work though?

Note that I have a side package that use code-generation to write hook classes as functions instead https://github.com/rrousselGit/functional_widget

```
@hwidget
Widget myWidget() {
  final state1Val - useState(...);

  return Text('hello ${state1Val.value}');
}
```

**Comment by cgestes** [comment]
I know about functional widget :)  They are practical for small widget, but I run in the same issue of passing a lot of arguments with big widget using them.

I'll try to propose something. Last time I tried something I was not satisfied..

**Comment by cgestes** [comment]
I wanted to avoid functional widget... but I guess that's the only way to go. Every attempt I make ends up being a functional widget with lots of function inside...

I don't see a less verbose solution...

```dart
@widget
Widget MyWidget(BuildContext context) {
  // declare all the states
  
  // declare callbacks (that can use states and context)

  // optionally declare build functions to handle complex widget creation

  // call the build functions depending on the state
}

Thank you :)

**Comment by cgestes** [comment]
Which can also be done with a normal hook widget... putting everything in the build function as if it was a functional widget.

**Comment by rrousselGit** [comment]
Right, but declaring functions inside build/functional widget is intended. That's what React recommends to do.

It makes the class pointless, true. But that's also why `functional_widget` is there.

I'm not sure how we could improve the syntax _without_ functional_widget.

**Comment by cgestes** [comment]
Same conclusion for me...

**Comment by esDotDev** [comment]
It is sad because the parameter passing kinda kills this for me, especially as everything has this long ValueNotifier<> syntax. This is made worse if you want to have discrete button handlers, as now you have to pass everything around twice. Once to the builder, another to the logic handler.

It makes standard flutter patterns like sub-build methods, or splitting into smaller widgets, very unattractive.  And only really seems to work nice and cleanly is when you just keep everything in some mammoth function. Which is just inherently kinda inflexible and not really great for scaling...

What would be amazing would be the ability to use the power of hooks, without sacrificing the ease and flexibility of having some central state. 

imo, hooks shines when it's managing routine tasks that are high in line count, and prone to bugs, like managing controllers, or streams, but it doesn't really provide any benefits at all when it comes to using **useState()**, other than saving me some calls to setState(). And for that it actually creates a bunch of headaches, or at least excessive typing...

**Comment by rrousselGit** [comment]
You should declare your methods in the body of the `build` function. That is _desired_
