### ISSUE TITLE
use DeepCollectionEquality for hook keys

### ISSUE THREAD

**Issue by rrousselGit** [rrousselGit/flutter_hooks#155]

**Comment by jezsung** [comment]
@rrousselGit 
I was looking for how equality works for hook keys and found this issue. Not quite sure if using deep collection equality by default is a good idea. Is this how React Hook works?

**Comment by rrousselGit** [comment]
I don't remember. And honestly at that point, this issue doesn't really matter.

I'm not sure it's worth making a change now.

**Comment by jezsung** [comment]
React Hook uses [`Object.is()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/is) comparison which is not the same as the `DeepCollectionEquality`.

I think this change is unnecessary.

**Comment by jezsung** [comment]
The only differences between `Object.is()` and Dart `==` comparison are the following:

- `NaN` comparison
- `0` and `-0` comparison (Dart doesn't have `+0`)

`Object.is()`
```js
Object.is(NaN, NaN) // true
Object.is(0, -0) // false
```

Dart `==`
```dart
double.nan == double.nan // false
0 == -0 // true
```

In order to exactly mimic the behavior of React Hook, the following changes seem to be needed:

``` dart
// Special case for NaN
if (a.isNaN && b.isNaN) {
  return true;
}

// Special case for 0 and -0
if (a == 0 && b == 0) {
  return (1 / a) == (1 / b);
}
```

Technically, this would be a breaking change but since comparing those values are quite rare, could be worth it to make this change. What do you think @rrousselGit?

**Comment by rrousselGit** [comment]
These sound like valuable changes.

For 0/-0, I'd rely on .isNegative

**Comment by jezsung** [comment]
`isNegative` seems better. I'll make a PR shortly
