### ISSUE TITLE
Guidance on memoization versus custom hook

### ISSUE THREAD

**Issue by scopendo** [rrousselGit/flutter_hooks#170]
I'm coming to grips with hooks and wondered if there is a general rule on when to use hook composition versus creating a new hook class?  For example, I wanted a page controller hook and so I've implemented the following, which seems to be working fine but is different to the approach taken by the package's standard `useTabController` hook function.

```dart
/// Hook function that creates a page controller that is automatically
/// disposed when the widget is disposed.
///
PageController usePageController({int initialPage = 0}) {
  final pageController = useMemoized(() => PageController(initialPage: initialPage));
  useEffect(() => pageController.dispose, [
    pageController
  ]);
  return pageController;
}
```

I've also extended `HookWidget` so that all of my hook widgets have a getter that returns a helper object for accessing commonly needed objects from the widget tree, such as the theme and media size.

Is there a more idiomatic way to achieve this with Flutter Hooks?

```dart
/// An alternative to [HookWidget] that provides access to a helper object
/// for accessing commonly requested data in the widget tree.
///
/// ```dart
///   class MyWidget extends MyHookWidget {
///     @override
///     Widget build(BuildContext context) {
///       return Container(
///         width: $.media.size.width / 2,
///         height: $.size.height / 2,
///         color: $.theme.primaryColor,
///         child: Text("Example", style: $.textTheme.headline6),
///       );
///     }
///   }
/// ```
///
abstract class MyHookWidget extends HookWidget {
  MyHookWidgetHelper get $ => useMemoized(() => MyHookWidgetHelper());
}

/// Helper for hook widgets that makes it easy to access inherited data, such as
/// the current [ThemeData] and [MediaQueryData]. Can be obtained by extending
/// [MyHookWidget] instead of [HookWidget].
///
/// Data is only subscribed to if requested.
///
class MyHookWidgetHelper {
  BuildContext _context;
  ThemeData _theme;
  MediaQueryData _media;

  /// The current [BuildContext].
  BuildContext get context => _context ?? (_context = useContext());

  /// The current [ThemeData].
  ThemeData get theme => _theme ?? (_theme = Theme.of(context));

  /// The [TextTheme] of the current [ThemeData].
  TextTheme get textTheme => theme.textTheme;

  /// The current [MediaQueryData].
  MediaQueryData get media => _media ?? (_media = MediaQuery.of(context));

  /// The [Size] of the current [MediaQueryData].
  Size get size => media.size;

  T watch<T>() => Provider.of<T>(context);
}
```

**Comment by davidmartos96** [comment]
@scopendo I would say that a more idiomatic way to do it would be to create separate hooks for the things you need, using the convention `useSomething`. Otherwise, for someone reading the code, it could not be clear that the dollar sign is calling a hook under the hood. That may be problematic because if moved around, you could start breaking the Rules of Hooks.
An example of custom hook could be:

```dart
ThemeData useTheme() {
  final context = useContext();
  return Theme.of(context);
}
```

```dart
TextTheme useTextTheme() {
  return useTheme().textTheme;
}
```

A similar technique could be used for your other examples.

**Comment by rrousselGit** [comment]
I wouldn't recommend comparing your custom hooks with the custom hooks shipped by `flutter_hooks`.

When making "core" hooks, `flutter_hooks` always use the class syntax for the sake of hot-reload.
It's a big inconvenience in boilerplate for a tiny gain. But rather than reducing the number of lines in the core, I prefer to focus on giving these tiny gains to users.

For custom hooks made by in your own applications, just use the function syntax.
