### ISSUE TITLE
useState don't rebuild this screen when value is changed

### ISSUE THREAD

**Issue by Abouassi98** [rrousselGit/flutter_hooks#274]
![image](https://user-images.githubusercontent.com/53384802/144742044-c2f0fa7b-39bb-48b5-a65a-7537a60edd05.png)

**Comment by davidmartos96** [comment]
The problem is that you are mutating the list, but reusing the same instance. Value notifier cannot tell if something changes inside the list.
You need to create a new list everytime you make a change or use a immutable list data structure from a external package like https://pub.dev/packages/fast_immutable_collections

**Comment by rrousselGit** [comment]
As mentioned by David, you're not actually changing `value`. You're mutating it.


You should update your code to be something closer to:

```dart
selected.value = [
  ...selected.value,
  newValue,
]
```

**Comment by Jakemangan** [comment]
Just used this issue to fix I problem I had with the same thing. 

This should really be added to the useState docs, even if it's actually something that is an attribute of ValueNotifier. Would probably save a lot of headaches.
