### ISSUE TITLE
Is it possible to add useAutoScrollController?

### ISSUE THREAD

**Issue by xzghx** [rrousselGit/flutter_hooks#364]
Hi,
Is it possible to add useAutoScrollController?
I use [scroll_to_index](https://pub.dev/packages/scroll_to_index) package for list view scrolling and I would like to instantiate it's controller which is of type AutoScrollController in hook.

**Comment by rrousselGit** [comment]
Sure. Feel free to make a PR

**Comment by rrousselGit** [comment]
Wait, sorry, I misunderstood what this is about.

No. Since AutoScrollController is from a package instead of Flutter itself, it does not belong in flutter_hooks.

But you could ask the author of the package you're using to package a hook package for [scroll_to_index](https://pub.dev/packages/scroll_to_index).
Or you could make the hook yourself in your project.
