### ISSUE TITLE
Remove calls to `super.lifecycle` in existing hooks

### ISSUE THREAD

**Issue by felangel** [rrousselGit/flutter_hooks#75]
In `_AnimationControllerHookState` the `dispose` override calls `super.dispose` before disposing the animation controller.

```dart
@override
 void dispose() {
   super.dispose();
   _animationController.dispose();
 }
```

I would expect the animation controller to be disposed first.

```dart
@override
 void dispose() {
   _animationController.dispose();
   super.dispose();
 }
```

Is this intentional? Thanks and great work 👍

**Comment by rrousselGit** [comment]
To be fair, it doesn't matter. `super.dispose` do _nothing_, and we'll never use mixins on hooks. Since hooks _are_ mixins. 

Originally all hooks life-cycles were decorated by `@mustCallSuper`, but after some thoughts, this is was unnecessary and removed. But I forgot to remove all the `super` calls made by existing hooks.

**Comment by felangel** [comment]
Oh interesting...I'll have to dig deeper into the hooks implementation to better understand how they work. If it's not needed then feel free to close the issue and decline the PR. Thanks 👍

**Comment by rrousselGit** [comment]
I'll keep this open as a reminder to clean this up. 😄
